### ISSUE TITLE
Log transmission monitoring

### ISSUE THREAD

**Issue by endepointe** [SecurityLogMiner/log-collection-backend#13]
# **User story statement:** 
> “As a blueteam member, I want to be notified of drops in client-server connectivity so that the log processing can be recovered without a loss of time or data.”

# **Background:**
### **Why do we want it?**
We want to be able to recover from failures expeditiously.

### **Who is this for?**
Blueteam members and their clients.

### **Do we have data to support it?** 
Yes, loss of availability affects the security of a system.

# **Solution/Requirements:**
- Ping/Pong between client and server using low-latency communication channel (socket?) If one does not ping (or pong), there might be an issue.
- Push notification and/or system status dashboard

# **Design resources (if any)**
[The system design ](https://github.com/SecurityLogMiner/log-collection-client/blob/log-entry-read/log-collection-backend.drawio.png)

# **Dependencies:**
- socket deps
- Front-end dashboard for visual system status (svelte?)
- Push Notifications

# **Tasks**
- [ ] *Establish Client-Server Connection*: Establish socket connection between client and server.
- [ ] *Create Log Chunks*: Collect log data in specific chunks on the client.
- [ ] *Order Log Chunks*: Develop a system for storing an array of chunks to be transmitted.
- [ ] *Create Checksum*: Once chunk size is met, create checksum of data and transmit over WS.
- [ ] *Transmission*: Server receives data, transmits checksum back to Client to ensure data was not lost.
- [ ] *Loss Protection*: If data was lost, retransmit the chunk while continuing to collect new chunks.
- [ ]  *Coding Reqs*: This transmission and verification stage may have to include use of threads and async operations.

# **Timeline**
6 weeks

# **Open Questions (if any)**
see discussion

# **Acceptance Criteria**
No data is lost during client-to-server transmission.

# **Definition of done**
Acceptance criteria is met and notifications are sent when there is degraded service.
